MySite/apps/bercoon/urls.py
from django.urls import path
from . import views


app_name = 'bercoon'
urlpatterns = [
    path('', views.index, name = 'index'),
    path('<int:article_id>/', views.detail, name='detail'),
    path('<int:article_id>/leave_comment/', views.leave_comment, name='leave_comment'),
]

MySite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('grappelli/', include('grappelli.urls')),
    path('admin/', admin.site.urls),
    path('', include('bercoon.urls')),
]

MySite/apps/bercoon/models.py
import datetime
from django.db import models

from django.utils import timezone

# Create your models here.

class Article(models.Model):
    article_title = models.CharField('Название статьи', max_length=200)
    article_text = models.TextField('Текст статьи')
    pub_date = models.DateTimeField('Дата публикации')

    def __str__(self):
        return self.article_title

    def was_published_recently(self):
        return self.pub_date >= (timezone.now() - datetime.timedelta(days=7))

    class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'

class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    autor_name = models.CharField('Имя автора', max_length=50)
    comment_text = models.CharField('Текст комментария', max_length=200)

    def __str__(self):
        return self.autor_name

    class Meta:
        verbose_name = 'Коментарий'
        verbose_name_plural = 'Коментарии'

MySite/apps/bercoon/views.py
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from .models import Article

def index(request):

    latest_article_list = Article.objects.order_by('pub_date')
    return render(request, 'bercoon/list.html', {'latest_article_list':latest_article_list})

def detail(request, article_id):
    try:
        a = Article.objects.get( id = article_id)
    except:
        raise Http404('Cnfnmz yt yfqltyf')
    latest_comment_list = a.comment_set.order_by('-id')[:10]

    return render(request, 'bercoon/detail.html', {'article':a, 'latest_comment_list':latest_comment_list})

def leave_comment(request, article_id):
    try:
        a = Article.objects.get( id = article_id)
    except:
        raise Http404('Cnfnmz yt yfqltyf')

    a.comment_set.create(autor_name = request.POST['name'], comment_text = request.POST['text'])

    return HttpResponseRedirect(reverse('bercoon:detail', args=(a.id,)))

MySite/templates/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Bercoon{% endblock %}</title>
</head>
<body>
    {% block content %}{% endblock %}
</body>
</html>

MySite/templates/bercoon/detail.html
{% extends 'base.html' %}

{% block title %}{{article.article_title}}{% endblock %}

{% block content %}
<h2>{{article.article_title}}</h2>

<p>{{article.article_text}}</p>

<em>{{article.pub_date}}</em>

{% if article.was_published_recently %}
    Новая статья
{% endif %}

<hr>
{% if latest_comment_list %}
    {% for c in latest_comment_list %}
        <p>
            <strong>{{c.autor_name}}</strong>
            <p>{{c.comment_text}}</p>
        </p>
    {% endfor %%}
{% else %}
    Комментариев пока нет!
{% endif %}
<hr>

<form action="{% url 'bercoon:leave_comment' article.id %}" method="POST">
    {% csrf_token %}
    <input type="text" required placeholder="Ваше имя" name="name"><br>
    <textarea name="text" required placeholder="Текст комментария" cols="30" rows="10"></textarea><br>

    <button type="submit">Оставить комментарий</button>
</form>

{% endblock %}

MySite/templates/bercoon/list.html
{% extends 'base.html' %}

{% block title %}Последние статьи{% endblock %}

{% block content %}
    {% if latest_article_list %}
        {% for a in latest_article_list %}
            <a href="{% url 'bercoon:detail' a.id %}">{{a.article_title}}</a>
        {% endfor %}
    {% else %}
        {{a.article_title}}
    {% endif %}

{% endblock %}